[workspace]
members = ["http", "http-server", "tcp-client", "tcp-server"]

[package]
name = "simple-networking-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
